name: Azure Pipelines Action

on:
  pull_request:
    branches:
      - master
      - releases/*

stages:
- stage: A
  jobs:
  - job: Build across platforms
  - job: Test across platforms    
- stage: B