name: Azure Pipelines Action

on:
  pull_request:
    branches:
      - master
      - releases/*

stages:
- stage: A build
    name: 'Build across platforms'
    steps:
      - uses: actions/checkout@v1
    
      - name: Install Lerna
        run: sudo yarn global add lerna@3.18.2 
