name: Azure Pipelines Action

on:
  push: 
    branches:
    - master
    - releases/*
  pull_request:
    branches:
      - master
      - releases/*
        
jobs:
  build_windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Install Lerna
      run: yarn global add lerna 
    
    - name: Install package dependencies
      run: yarn install --frozen-lockfile
    
    - name: action-lerna
      uses: m19c/action-lerna@1.0.0
    
    - name: Build Yarn workspaces
      run: lerna run prepare
      
    - name: Ensure Prettier formatting
      run: lerna run prettier:diff
      
    - name: Execute unit tests
      run: lerna run test --stream
      timeout-minutes: 20
    
  build_macos:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Install Lerna
      run: sudo yarn global add lerna@3.18.2  
    
    - name: Install package dependencies
      run: yarn install --frozen-lockfile
    
    - name: Build Yarn workspaces
      run: lerna run prepare
      
    - name: Ensure Prettier formatting
      run: lerna run prettier:diff
      
    - name: Execute unit tests
      run: lerna run test --stream
      timeout-minutes: 20

  build_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Install Lerna
      run: sudo yarn global add lerna@3.18.2  
    
    - name: Install package dependencies
      run: yarn install --frozen-lockfile
    
    - name: Build Yarn workspaces
      run: lerna run prepare
      
    - name: Ensure Prettier formatting
      run: lerna run prettier:diff
      
    - name: Execute unit tests
      run: lerna run test --stream
      timeout-minutes: 20