name: FAST Workflows - Component Explorer

on:
  push: 
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build_linux:
    runs-on: ubuntu-latest
    env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TEST_REPORTER_ID }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Lerna
      run: sudo yarn global add lerna@3.18.2  

    - name: Install package dependencies
      run: yarn install --frozen-lockfile

    - name: Build Yarn workspaces
      run: lerna run prepare

    - name: Testing Prettier format
      run: lerna run prettier:diff

    - name: Testing unit tests
      run: lerna run test --stream

    - name: Compile Component Explorer
      run: yarn run build.app

    - name: Publish Pipeline Artifact
      inputs:
        targetPath: 'packages/fast-component-explorer/www'

    
        